import type { Product, PaymentMethod } from './types';

export const products: Product[] = [
  {
    id: 'lanche-1',
    name: 'MISTO',
    description: 'Sanduíche tradicional da Sandubaria',
    price: 10.00,
    category: 'lanche',
    emoji: '🍔',
  },
  {
    id: 'lanche-2',
    name: 'BAURU',
    description: 'Sanduíche tradicional da Sandubaria',
    price: 10.00,
    category: 'lanche',
    emoji: '🍔',
  },
  {
    id: 'lanche-3',
    name: 'QUEIJO QUENTE',
    description: 'Sanduíche tradicional da Sandubaria',
    price: 10.00,
    category: 'lanche',
    emoji: '🍔',
  },
  {
    id: 'lanche-4',
    name: 'HAMBÚRGUER',
    description: 'Sanduíche tradicional da Sandubaria',
    price: 15.00,
    category: 'lanche',
    emoji: '🍔',
  },
  {
    id: 'lanche-5',
    name: 'AMERICANO',
    description: 'Sanduíche tradicional da Sandubaria',
    price: 15.00,
    category: 'lanche',
    emoji: '🍔',
  },
  {
    id: 'lanche-6',
    name: 'X-BURGUER',
    description: 'Sanduíche tradicional da Sandubaria',
    price: 16.00,
    category: 'lanche',
    emoji: '🍔',
  },
  {
    id: 'lanche-7',
    name: 'MUNIANO',
    description: 'Sanduíche da Sandubaria',
    price: 18.00,
    category: 'lanche',
    emoji: '🍔',
  },
  {
    id: 'lanche-8',
    name: 'X-CALABRESA',
    description: 'Sanduíche da Sandubaria',
    price: 20.00,
    category: 'lanche',
    emoji: '🍔',
  },
  {
    id: 'lanche-9',
    name: 'X-BACON',
    description: 'Sanduíche da Sandubaria',
    price: 20.00,
    category: 'lanche',
    emoji: '🍔',
  },
  {
    id: 'lanche-10',
    name: 'X-COMERCIAL',
    description: 'Sanduíche da Sandubaria',
    price: 20.00,
    category: 'lanche',
    emoji: '🍔',
  },
  {
    id: 'lanche-11',
    name: 'NAPOLITANO',
    description: 'Sanduíche da Sandubaria',
    price: 23.00,
    category: 'lanche',
    emoji: '🍔',
  },
  {
    id: 'lanche-12',
    name: 'IDEAL',
    description: 'Especial da Sandubaria',
    price: 20.00,
    category: 'lanche',
    emoji: '🍔',
  },
  {
    id: 'lanche-13',
    name: 'IDEAL FRANGO',
    description: 'Especial da Sandubaria',
    price: 23.00,
    category: 'lanche',
    emoji: '🍔',
  },
  {
    id: 'lanche-14',
    name: 'X-FILÉ DE FRANGO',
    description: 'Especial da Sandubaria',
    price: 22.00,
    category: 'lanche',
    emoji: '🍔',
  },
  {
    id: 'lanche-15',
    name: 'X-FILÉ DE CARNE',
    description: 'Especial da Sandubaria',
    price: 22.00,
    category: 'lanche',
    emoji: '🍔',
  },
  {
    id: 'lanche-16',
    name: 'X-FILÉ DE FRANGO BACON',
    description: 'Especial da Sandubaria',
    price: 24.00,
    category: 'lanche',
    emoji: '🍔',
  },
  {
    id: 'lanche-17',
    name: 'X-FILÉ DE FRANGO CARNE',
    description: 'Especial da Sandubaria',
    price: 24.00,
    category: 'lanche',
    emoji: '🍔',
  },
  {
    id: 'lanche-18',
    name: 'X-FILÉ CARNE BACON',
    description: 'Especial da Sandubaria',
    price: 24.00,
    category: 'lanche',
    emoji: '🍔',
  },
  {
    id: 'lanche-19',
    name: 'X-TUDO',
    description: 'Especial da Sandubaria',
    price: 25.00,
    category: 'lanche',
    emoji: '🍔',
  },
  {
    id: 'lanche-20',
    name: 'BIZ BURGUER',
    description: 'Especial da Sandubaria',
    price: 26.00,
    category: 'lanche',
    emoji: '🍔',
  },
  {
    id: 'lanche-21',
    name: 'X-DUPLO',
    description: 'Especial da Sandubaria',
    price: 28.00,
    category: 'lanche',
    emoji: '🍔',
  },
  {
    id: 'lanche-22',
    name: 'PASSAPORTE DE FRANGO',
    description: 'Sanduíche do passaporte da Sandubaria',
    price: 22.00,
    category: 'lanche',
    emoji: '🌭',
  },
  {
    id: 'lanche-23',
    name: 'PASSAPORTE DE CARNE',
    description: 'Sanduíche do passaporte da Sandubaria',
    price: 22.00,
    category: 'lanche',
    emoji: '🌭',
  },
  {
    id: 'lanche-24',
    name: 'PASSAPORTE DE MISTO',
    description: 'Sanduíche do passaporte da Sandubaria',
    price: 25.00,
    category: 'lanche',
    emoji: '🌭',
  },
  {
    id: 'acompanhamento-1',
    name: 'BATATA FRITA P',
    description: 'Porção de batata frita',
    price: 10.00,
    category: 'acompanhamento',
    emoji: '🍟',
  },
  {
    id: 'acompanhamento-2',
    name: 'BATATA FRITA G',
    description: 'Porção de batata frita',
    price: 15.00,
    category: 'acompanhamento',
    emoji: '🍟',
  },
  {
    id: 'acompanhamento-3',
    name: 'PORÇÃO (PETISCO)',
    description: 'Porção petisco da Sandubaria',
    price: 25.00,
    category: 'acompanhamento',
    emoji: '🍟',
  },
  {
    id: 'bebida-1',
    name: 'COCA-COLA 350ML',
    description: 'Refrigerante gelado',
    price: 6.00,
    category: 'bebida',
    emoji: '🥤',
  },
  {
    id: 'bebida-2',
    name: 'FANTA 350ML',
    description: 'Refrigerante gelado',
    price: 6.00,
    category: 'bebida',
    emoji: '🥤',
  },
  {
    id: 'bebida-3',
    name: 'GUARANÁ 350ML',
    description: 'Refrigerante gelado',
    price: 6.00,
    category: 'bebida',
    emoji: '🥤',
  },
  {
    id: 'bebida-4',
    name: 'COCA-COLA 1L',
    description: 'Refrigerante gelado',
    price: 10.00,
    category: 'bebida',
    emoji: '🥤',
  },
  {
    id: 'bebida-5',
    name: 'GUARANÁ 1L',
    description: 'Refrigerante gelado',
    price: 10.00,
    category: 'bebida',
    emoji: '🥤',
  },
  {
    id: 'bebida-6',
    name: 'COCA-COLA 2L',
    description: 'Refrigerante gelado',
    price: 15.00,
    category: 'bebida',
    emoji: '🥤',
  },
];

export const paymentMethods: { id: PaymentMethod; name: string; emoji: string }[] = [
  { id: 'dinheiro', name: 'Dinheiro', emoji: '💵' },
  { id: 'cartao-credito', name: 'Cartão Crédito', emoji: '💳' },
  { id: 'cartao-debito', name: 'Cartão Débito', emoji: '💳' },
  { id: 'pix', name: 'PIX', emoji: '📱' },
];

export const stepLabels: Record<string, { label: string; number: number }> = {
  lanches: { label: 'Lanches', number: 1 },
  bebidas: { label: 'Bebidas', number: 2 },
  acompanhamentos: { label: 'Acompanhamentos', number: 3 },
  observacoes: { label: 'Observações', number: 4 },
  pagamento: { label: 'Pagamento', number: 5 },
  confirmacao: { label: 'Confirmação', number: 6 },
};

export function formatCurrency(value: number): string {
  return value.toLocaleString('pt-BR', {
    style: 'currency',
    currency: 'BRL',
  });
}
